services:
  pipeline:
    image: ghcr.io/yodakatstuno/rnaseq-pipeline:v1.3.0
    working_dir: /app
    environment:
      R_LIBS_USER: /app/.r_libs
      PIPELINE_OUTPUT_DIR: /app/Output
    user: "${UID:-0}:${GID:-0}"
    volumes:
      # プログラム（.pyや.R）だけをマウントし、.r_libs はマウントしない
      - ./main_pipeline.py:/app/main_pipeline.py
      - ./R:/app/R
      - ./dependencies:/app/dependencies
      - ./data:/data
      - ${HOME}/Output:/app/Output
    tty: true
    stdin_open: true
